name: Yooper's PHP Text Analysis
description:  PHP Text Analysis is a library for performing Information Retrival (IR) and Natural Language Processing (NLP) tasks using the PHP language.

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: http://yooper.github.io/php-text-analysis/
permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: https://github.com/yooper/php-text-analysis
    disqus_shortname: #

ga_id: #
ga_username: #

timezone: 